{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "27aef5cf-091b-4b7c-8a36-c34bc2bef6fd",
   "metadata": {},
   "source": [
    "# Exploratory Data Analysis\n",
    "\n",
    "Understanding the dataset structure and relationships between procurement, sales, pricing, and inventory data to prepare an analytics-ready dataset.\n",
    "\n",
    "The objective is to explore how the data is distributed across multiple transactional tables and determine whether aggregated analytical tables are required for efficient reporting and analysis.\n",
    "\n",
    "This process helps support:\n",
    "- Vendor performance evaluation\n",
    "- Profitability analysis\n",
    "- Product pricing optimization\n",
    "- Inventory and sales tracking\n",
    "- Faster dashboard reporting and business analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f41bea7d-3960-4cb6-9a74-ac14aad38a98",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Table 'begin_inventory' optimized and loaded.\n",
      "✅ Table 'end_inventory' optimized and loaded.\n",
      "✅ Table 'purchases' optimized and loaded.\n",
      "✅ Table 'purchase_prices' optimized and loaded.\n",
      "✅ Table 'sales' optimized and loaded.\n",
      "✅ Table 'vendor_invoice' optimized and loaded.\n",
      "\n",
      "🏆 inventory.db created successfully!\n"
     ]
    }
   ],
   "source": [
    "# Step 1: Data Ingestion (The \"Engine\")\n",
    "\n",
    "import pandas as pd\n",
    "import sqlite3\n",
    "import os\n",
    "\n",
    "# Project folder\n",
    "project_path = r\"C:\\Users\\ASUS\\Desktop\\_aPortfolioProjects\\VendorPerformanceAnalysis\"\n",
    "\n",
    "# Database path\n",
    "db_path = os.path.join(project_path, \"inventory.db\")\n",
    "\n",
    "# Dataset folder path\n",
    "data_path = os.path.join(project_path, \"Data\")\n",
    "\n",
    "# Connect SQLite database\n",
    "conn = sqlite3.connect(db_path)\n",
    "\n",
    "# Process each CSV file\n",
    "for file in os.listdir(data_path):\n",
    "    if file.endswith('.csv'):\n",
    "        table_name = file.replace('.csv', '')\n",
    "\n",
    "        file_path = os.path.join(data_path, file)\n",
    "\n",
    "        # Read CSV\n",
    "        df = pd.read_csv(file_path, encoding='ISO-8859-1', low_memory=False)\n",
    "\n",
    "        # Clean column names\n",
    "        df.columns = [c.strip().replace(' ', '_') for c in df.columns]\n",
    "\n",
    "        # Load into SQLite\n",
    "        df.to_sql(table_name, conn, if_exists='replace', index=False)\n",
    "\n",
    "        print(f\"✅ Table '{table_name}' optimized and loaded.\")\n",
    "\n",
    "conn.close()\n",
    "\n",
    "print(\"\\n🏆 inventory.db created successfully!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41b23459-9262-4a7b-9a9f-756ac6f3d2f4",
   "metadata": {},
   "source": [
    "### Data Ingestion & Standardization\n",
    "\n",
    "The raw CSV files were loaded into SQLite to create a centralized relational database environment.\n",
    "\n",
    "Key improvements during ingestion:\n",
    "- Standardized column names for consistency\n",
    "- Handled encoding issues for special characters\n",
    "- Optimized memory usage for large datasets\n",
    "- Converted flat files into queryable relational tables\n",
    "\n",
    "This step establishes a scalable and structured foundation for advanced SQL analytics."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "07cd310e-df3c-480c-813e-3df00b431b85",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Indexes created successfully!\n"
     ]
    }
   ],
   "source": [
    "# Step 2 : The Optimization (Indexes)\n",
    "\n",
    "import sqlite3\n",
    "\n",
    "db_path = r\"C:\\Users\\ASUS\\Desktop\\_aPortfolioProjects\\VendorPerformanceAnalysis\\inventory.db\"\n",
    "\n",
    "conn = sqlite3.connect(db_path)\n",
    "\n",
    "cursor = conn.cursor()\n",
    "\n",
    "cursor.executescript(\"\"\"\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_purchases_vendor_brand\n",
    "ON purchases(VendorNumber, Brand);\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_sales_vendor_brand\n",
    "ON sales(VendorNo, Brand);\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_purchase_prices_vendor_brand\n",
    "ON purchase_prices(VendorNumber, Brand);\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_vendor_invoice_vendor\n",
    "ON vendor_invoice(VendorNumber);\n",
    "\n",
    "\"\"\")\n",
    "\n",
    "conn.commit()\n",
    "conn.close()\n",
    "\n",
    "print(\"✅ Indexes created successfully!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "20cd1676-4607-4388-b3bc-b9c87ecac882",
   "metadata": {},
   "source": [
    "### Query Performance Optimization\n",
    "\n",
    "Indexes were created on frequently used join keys such as VendorNumber and Brand.\n",
    "\n",
    "Business Benefits:\n",
    "- Faster query execution on large transactional datasets\n",
    "- Improved performance for joins and aggregations\n",
    "- Reduced dashboard refresh time\n",
    "- More efficient analytics processing\n",
    "\n",
    "This optimization is important because procurement and sales tables contain high-volume transactional records."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "29d00645-fc96-44ed-b347-91ed278a8fad",
   "metadata": {},
   "source": [
    "### Creating the Vendor Performance Master Table\n",
    "\n",
    "The core business data was spread across multiple operational tables:\n",
    "- Purchases → procurement activity\n",
    "- Sales → revenue generation\n",
    "- Purchase Prices → vendor pricing information\n",
    "\n",
    "To simplify analysis, a centralized master table was created by aggregating:\n",
    "- Vendor purchases\n",
    "- Sales performance\n",
    "- Product pricing\n",
    "- Inventory movement\n",
    "\n",
    "This enables vendor-level and brand-level performance analysis from a single analytical dataset."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "c89af720-39b6-42db-b746-cf70d1c7d949",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "💎 Advanced Master Table Created with Quality Filters and Stable Pricing!\n"
     ]
    }
   ],
   "source": [
    "# Step 3: The Master Table (The \"Brain\")\n",
    "\n",
    "conn = sqlite3.connect( r\"C:\\Users\\ASUS\\Desktop\\_aPortfolioProjects\\VendorPerformanceAnalysis\\inventory.db\")\n",
    "advanced_sql = \"\"\"\n",
    "DROP TABLE IF EXISTS vendor_performance_master;\n",
    "CREATE TABLE vendor_performance_master AS\n",
    "WITH SalesAgg AS (\n",
    "    SELECT \n",
    "        VendorNo, Brand, \n",
    "        SUM(SalesQuantity) AS TotalQtySold, \n",
    "        SUM(SalesDollars) AS TotalRevenue\n",
    "    FROM sales \n",
    "    GROUP BY 1, 2\n",
    "),\n",
    "PurchaseAgg AS (\n",
    "    SELECT \n",
    "        p.VendorNumber, \n",
    "        TRIM(p.VendorName) AS VendorName, \n",
    "        p.Brand, \n",
    "        TRIM(p.Description) AS Description,\n",
    "        /* IMPROVEMENT 2: Use AVG to avoid duplicate rows if prices vary slightly */\n",
    "        AVG(pp.Price) AS ListPrice,\n",
    "        AVG(p.PurchasePrice) AS ActualPaidPrice,\n",
    "        SUM(p.Quantity) AS TotalQtyPurchased,\n",
    "        SUM(p.Dollars) AS TotalSpend\n",
    "    FROM purchases p\n",
    "    JOIN purchase_prices pp ON p.Brand = pp.Brand AND p.VendorNumber = pp.VendorNumber\n",
    "    /* IMPROVEMENT 3: Data Quality Filters */\n",
    "    WHERE p.Quantity > 0 AND p.Dollars > 0 AND p.PurchasePrice > 0\n",
    "    GROUP BY 1, 2, 3, 4\n",
    ")\n",
    "SELECT \n",
    "    pa.*,\n",
    "    COALESCE(sa.TotalQtySold, 0) AS TotalQtySold,\n",
    "    COALESCE(sa.TotalRevenue, 0) AS TotalRevenue,\n",
    "    (pa.ActualPaidPrice - pa.ListPrice) AS PriceVariance,\n",
    "    CASE \n",
    "        WHEN pa.TotalQtyPurchased > 0 THEN CAST(COALESCE(sa.TotalQtySold, 0) AS FLOAT) / pa.TotalQtyPurchased \n",
    "        ELSE 0 \n",
    "    END AS SellThroughRate\n",
    "FROM PurchaseAgg pa\n",
    "LEFT JOIN SalesAgg sa ON pa.VendorNumber = sa.VendorNo AND pa.Brand = sa.Brand;\n",
    "\"\"\"\n",
    "\n",
    "curr = conn.cursor()\n",
    "# IMPROVEMENT: Using executescript for multiple statements\n",
    "curr.executescript(advanced_sql)\n",
    "conn.close()\n",
    "print(\"💎 Advanced Master Table Created with Quality Filters and Stable Pricing!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7c37499c-96e2-4836-ae80-ecf37688b338",
   "metadata": {},
   "source": [
    "### Business Logic & Data Quality Enhancements\n",
    "\n",
    "Several improvements were applied while building the master table:\n",
    "\n",
    "- Used composite joins (VendorNumber + Brand) for accurate mapping\n",
    "- Applied data quality filters to remove invalid transactions\n",
    "- Used average pricing logic to stabilize price fluctuations\n",
    "- Calculated sell-through rate to measure inventory movement\n",
    "- Added price variance analysis to evaluate vendor pricing efficiency\n",
    "\n",
    "These transformations improve both analytical accuracy and business reliability."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bc50b188-1c9f-447f-bbc2-28f25fed82ad",
   "metadata": {},
   "source": [
    "### Building the Final Analytics Layer\n",
    "\n",
    "A final analytics-ready table was created to support:\n",
    "- Exploratory Data Analysis (EDA)\n",
    "- Statistical analysis\n",
    "- Power BI dashboarding\n",
    "- Vendor profitability evaluation\n",
    "\n",
    "The table includes advanced business KPIs such as:\n",
    "- Net Profit\n",
    "- Net Profit Margin\n",
    "- Freight Per Unit\n",
    "- Remaining Inventory\n",
    "- Unsold Inventory Value\n",
    "- Sales-to-Purchase Ratio\n",
    "\n",
    "Creating a pre-aggregated analytical table improves reporting speed and avoids repeated heavy SQL computations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "0f130a9e-567e-43dd-8083-6508a7b2e397",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🏆 Final Table for Power BI is Ready and Exported to CSV!\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>VendorNumber</th>\n",
       "      <th>VendorName</th>\n",
       "      <th>Brand</th>\n",
       "      <th>Description</th>\n",
       "      <th>ListPrice</th>\n",
       "      <th>ActualPaidPrice</th>\n",
       "      <th>TotalQtyPurchased</th>\n",
       "      <th>TotalSpend</th>\n",
       "      <th>TotalQtySold</th>\n",
       "      <th>TotalRevenue</th>\n",
       "      <th>PriceVariance</th>\n",
       "      <th>SellThroughRate</th>\n",
       "      <th>TotalFreight</th>\n",
       "      <th>RemainingStock</th>\n",
       "      <th>UnsoldInventoryValue</th>\n",
       "      <th>FreightPerUnit</th>\n",
       "      <th>NetProfit</th>\n",
       "      <th>NetProfitMargin</th>\n",
       "      <th>GrossProfit</th>\n",
       "      <th>SalesToPurchaseRatio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>IRA GOLDMAN AND WILLIAMS, LLP</td>\n",
       "      <td>90085</td>\n",
       "      <td>Ch Lilian 09 Ladouys St Este</td>\n",
       "      <td>36.99</td>\n",
       "      <td>23.86</td>\n",
       "      <td>8</td>\n",
       "      <td>190.88</td>\n",
       "      <td>18</td>\n",
       "      <td>665.82</td>\n",
       "      <td>-13.13</td>\n",
       "      <td>2.250000</td>\n",
       "      <td>27.08</td>\n",
       "      <td>-10</td>\n",
       "      <td>-238.60</td>\n",
       "      <td>3.385000</td>\n",
       "      <td>447.86</td>\n",
       "      <td>67.264426</td>\n",
       "      <td>474.94</td>\n",
       "      <td>3.488160</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>IRA GOLDMAN AND WILLIAMS, LLP</td>\n",
       "      <td>90609</td>\n",
       "      <td>Flavor Essence Variety 5 Pak</td>\n",
       "      <td>24.99</td>\n",
       "      <td>17.00</td>\n",
       "      <td>320</td>\n",
       "      <td>5440.00</td>\n",
       "      <td>24</td>\n",
       "      <td>599.76</td>\n",
       "      <td>-7.99</td>\n",
       "      <td>0.075000</td>\n",
       "      <td>27.08</td>\n",
       "      <td>296</td>\n",
       "      <td>5032.00</td>\n",
       "      <td>0.084625</td>\n",
       "      <td>-4867.32</td>\n",
       "      <td>-811.544618</td>\n",
       "      <td>-4840.24</td>\n",
       "      <td>0.110250</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>54</td>\n",
       "      <td>AAPER ALCOHOL &amp; CHEMICAL CO</td>\n",
       "      <td>990</td>\n",
       "      <td>Ethyl Alcohol 200 Proof</td>\n",
       "      <td>134.49</td>\n",
       "      <td>105.07</td>\n",
       "      <td>1</td>\n",
       "      <td>105.07</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>-29.42</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.48</td>\n",
       "      <td>1</td>\n",
       "      <td>105.07</td>\n",
       "      <td>0.480000</td>\n",
       "      <td>-105.55</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>-105.07</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>60</td>\n",
       "      <td>ADAMBA IMPORTS INTL INC</td>\n",
       "      <td>771</td>\n",
       "      <td>Bak's Krupnik Honey Liqueur</td>\n",
       "      <td>14.99</td>\n",
       "      <td>11.44</td>\n",
       "      <td>39</td>\n",
       "      <td>446.16</td>\n",
       "      <td>47</td>\n",
       "      <td>704.53</td>\n",
       "      <td>-3.55</td>\n",
       "      <td>1.205128</td>\n",
       "      <td>367.52</td>\n",
       "      <td>-8</td>\n",
       "      <td>-91.52</td>\n",
       "      <td>9.423590</td>\n",
       "      <td>-109.15</td>\n",
       "      <td>-15.492598</td>\n",
       "      <td>258.37</td>\n",
       "      <td>1.579097</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>60</td>\n",
       "      <td>ADAMBA IMPORTS INTL INC</td>\n",
       "      <td>3401</td>\n",
       "      <td>Vesica Vodka</td>\n",
       "      <td>14.99</td>\n",
       "      <td>11.10</td>\n",
       "      <td>6</td>\n",
       "      <td>66.60</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>-3.89</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>367.52</td>\n",
       "      <td>6</td>\n",
       "      <td>66.60</td>\n",
       "      <td>61.253333</td>\n",
       "      <td>-434.12</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>-66.60</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   VendorNumber                     VendorName  Brand  \\\n",
       "0             2  IRA GOLDMAN AND WILLIAMS, LLP  90085   \n",
       "1             2  IRA GOLDMAN AND WILLIAMS, LLP  90609   \n",
       "2            54    AAPER ALCOHOL & CHEMICAL CO    990   \n",
       "3            60        ADAMBA IMPORTS INTL INC    771   \n",
       "4            60        ADAMBA IMPORTS INTL INC   3401   \n",
       "\n",
       "                    Description  ListPrice  ActualPaidPrice  \\\n",
       "0  Ch Lilian 09 Ladouys St Este      36.99            23.86   \n",
       "1  Flavor Essence Variety 5 Pak      24.99            17.00   \n",
       "2       Ethyl Alcohol 200 Proof     134.49           105.07   \n",
       "3   Bak's Krupnik Honey Liqueur      14.99            11.44   \n",
       "4                  Vesica Vodka      14.99            11.10   \n",
       "\n",
       "   TotalQtyPurchased  TotalSpend  TotalQtySold  TotalRevenue  PriceVariance  \\\n",
       "0                  8      190.88            18        665.82         -13.13   \n",
       "1                320     5440.00            24        599.76          -7.99   \n",
       "2                  1      105.07             0          0.00         -29.42   \n",
       "3                 39      446.16            47        704.53          -3.55   \n",
       "4                  6       66.60             0          0.00          -3.89   \n",
       "\n",
       "   SellThroughRate  TotalFreight  RemainingStock  UnsoldInventoryValue  \\\n",
       "0         2.250000         27.08             -10               -238.60   \n",
       "1         0.075000         27.08             296               5032.00   \n",
       "2         0.000000          0.48               1                105.07   \n",
       "3         1.205128        367.52              -8                -91.52   \n",
       "4         0.000000        367.52               6                 66.60   \n",
       "\n",
       "   FreightPerUnit  NetProfit  NetProfitMargin  GrossProfit  \\\n",
       "0        3.385000     447.86        67.264426       474.94   \n",
       "1        0.084625   -4867.32      -811.544618     -4840.24   \n",
       "2        0.480000    -105.55         0.000000      -105.07   \n",
       "3        9.423590    -109.15       -15.492598       258.37   \n",
       "4       61.253333    -434.12         0.000000       -66.60   \n",
       "\n",
       "   SalesToPurchaseRatio  \n",
       "0              3.488160  \n",
       "1              0.110250  \n",
       "2              0.000000  \n",
       "3              1.579097  \n",
       "4              0.000000  "
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Step 4: Final Analytics Table & Export\n",
    "\n",
    "conn = sqlite3.connect( r\"C:\\Users\\ASUS\\Desktop\\_aPortfolioProjects\\VendorPerformanceAnalysis\\inventory.db\")\n",
    "\n",
    "final_analysis_sql = \"\"\"\n",
    "DROP TABLE IF EXISTS final_vendor_analysis;\n",
    "CREATE TABLE final_vendor_analysis AS\n",
    "SELECT \n",
    "    v.*,\n",
    "    COALESCE(f.FreightCost, 0) AS TotalFreight,\n",
    "    /* IMPROVEMENT 1: Added New Business KPIs */\n",
    "    (v.TotalQtyPurchased - v.TotalQtySold) AS RemainingStock,\n",
    "    (v.TotalQtyPurchased - v.TotalQtySold) * v.ActualPaidPrice AS UnsoldInventoryValue,\n",
    "    CASE \n",
    "        WHEN v.TotalQtyPurchased > 0 THEN COALESCE(f.FreightCost, 0) * 1.0 / v.TotalQtyPurchased \n",
    "        ELSE 0 \n",
    "    END AS FreightPerUnit,\n",
    "    (v.TotalRevenue - v.TotalSpend - COALESCE(f.FreightCost, 0)) AS NetProfit,\n",
    "    CASE \n",
    "        WHEN v.TotalRevenue > 0 THEN ((v.TotalRevenue - v.TotalSpend - COALESCE(f.FreightCost, 0)) * 100.0 / v.TotalRevenue)\n",
    "        ELSE 0 \n",
    "    END AS NetProfitMargin,\n",
    "    /* Original Metrics */\n",
    "    (v.TotalRevenue - v.TotalSpend) AS GrossProfit,\n",
    "    CASE \n",
    "        WHEN v.TotalSpend > 0 THEN v.TotalRevenue * 1.0 / v.TotalSpend\n",
    "        ELSE 0 \n",
    "    END AS SalesToPurchaseRatio\n",
    "FROM vendor_performance_master v\n",
    "LEFT JOIN (\n",
    "    SELECT VendorNumber, SUM(Freight) as FreightCost \n",
    "    FROM vendor_invoice \n",
    "    GROUP BY 1\n",
    ") f ON v.VendorNumber = f.VendorNumber;\n",
    "\"\"\"\n",
    "\n",
    "curr = conn.cursor()\n",
    "curr.executescript(final_analysis_sql)\n",
    "\n",
    "# IMPROVEMENT 4: Export to CSV for Power BI\n",
    "final_df = pd.read_sql(\"SELECT * FROM final_vendor_analysis\", conn)\n",
    "final_df.to_csv( r\"C:\\Users\\ASUS\\Desktop\\_aPortfolioProjects\\VendorPerformanceAnalysis\\final_vendor_analysis.csv\", index=False)\n",
    "\n",
    "conn.close()\n",
    "print(\"🏆 Final Table for Power BI is Ready and Exported to CSV!\")\n",
    "final_df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5bd65f73-b07f-4f21-96c6-d3ebfa53d93f",
   "metadata": {},
   "source": [
    "### Final Output\n",
    "\n",
    "The cleaned and transformed dataset was exported as:\n",
    "\n",
    "`final_vendor_analysis.csv`\n",
    "\n",
    "This dataset serves as the single source of truth for:\n",
    "- Python-based EDA\n",
    "- Statistical analysis\n",
    "- Power BI dashboards\n",
    "- Business insight generation\n",
    "\n",
    "By centralizing all vendor KPIs into one table, reporting becomes faster, cleaner, and more scalable."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "bd834bcb-d834-4b56-b49b-0c3ae1c72173",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>VendorName</th>\n",
       "      <th>TotalSpend</th>\n",
       "      <th>TotalRevenue</th>\n",
       "      <th>SellThroughRate</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>BROWN-FORMAN CORP</td>\n",
       "      <td>3811251.60</td>\n",
       "      <td>5101919.51</td>\n",
       "      <td>0.979108</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>MARTIGNETTI COMPANIES</td>\n",
       "      <td>3804041.22</td>\n",
       "      <td>4819073.49</td>\n",
       "      <td>0.976890</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>PERNOD RICARD USA</td>\n",
       "      <td>3418303.68</td>\n",
       "      <td>4538120.60</td>\n",
       "      <td>0.998575</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>DIAGEO NORTH AMERICA INC</td>\n",
       "      <td>3261197.94</td>\n",
       "      <td>4475972.88</td>\n",
       "      <td>0.993703</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>DIAGEO NORTH AMERICA INC</td>\n",
       "      <td>3023206.01</td>\n",
       "      <td>4223107.62</td>\n",
       "      <td>0.983556</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 VendorName  TotalSpend  TotalRevenue  SellThroughRate\n",
       "0         BROWN-FORMAN CORP  3811251.60    5101919.51         0.979108\n",
       "1     MARTIGNETTI COMPANIES  3804041.22    4819073.49         0.976890\n",
       "2         PERNOD RICARD USA  3418303.68    4538120.60         0.998575\n",
       "3  DIAGEO NORTH AMERICA INC  3261197.94    4475972.88         0.993703\n",
       "4  DIAGEO NORTH AMERICA INC  3023206.01    4223107.62         0.983556"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Step 5: Validation (The \"Check\")\n",
    "\n",
    "conn = sqlite3.connect('inventory.db')\n",
    "query = \"SELECT VendorName, TotalSpend, TotalRevenue, SellThroughRate FROM vendor_performance_master ORDER BY TotalRevenue DESC LIMIT 5\"\n",
    "check_df = pd.read_sql(query, conn)\n",
    "conn.close()\n",
    "check_df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (TensorFlow)",
   "language": "python",
   "name": "tf_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
