{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "41aadecc-8602-479a-b83c-b664a09ed404",
   "metadata": {},
   "source": [
    "# Exploratory Data Analysis (EDA)\n",
    "\n",
    "The objective of this analysis is to explore vendor procurement, sales, inventory, and profitability data to uncover meaningful business patterns and operational insights.\n",
    "\n",
    "This EDA helps transform the analytical dataset into a decision-support system for identifying:\n",
    "- Vendor performance trends\n",
    "- Profitability drivers\n",
    "- Inventory and dead stock risks\n",
    "- Procurement efficiency opportunities\n",
    "- Pricing and sales optimization strategies\n",
    "- Supplier dependency and concentration risks\n",
    "\n",
    "The analysis also prepares a clean and analytics-ready dataset for:\n",
    "- Statistical analysis\n",
    "- Business intelligence reporting\n",
    "- Power BI dashboard development\n",
    "- Executive decision-making"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e467be4-0333-4008-a552-361b28260b59",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 1 ==================================\n",
    "# IMPORT LIBRARIES\n",
    "# =========================================\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import sqlite3\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "from scipy.stats import ttest_ind\n",
    "import scipy.stats as stats\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "pd.set_option('display.max_columns', None)\n",
    "\n",
    "sns.set_style(\"whitegrid\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e1ea3ffe-a12b-46c8-be88-788742a00dcb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 2 ==================================\n",
    "# DATABASE CONNECTION\n",
    "# =========================================\n",
    "\n",
    "conn = sqlite3.connect(\n",
    "    r\"C:\\Users\\ASUS\\Desktop\\_aPortfolioProjects\\Vendor Intelligence & Procurement Optimization Analytics System\\inventory.db\"\n",
    ")\n",
    "# Load Final Summary Table\n",
    "df = pd.read_sql_query(\"\"\"\n",
    "SELECT *\n",
    "FROM final_vendor_analysis\n",
    "\"\"\", conn)\n",
    "\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e38b209c-5f16-4896-9031-85e49e06d8b8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 3 ==================================\n",
    "# BASIC DATA UNDERSTANDING\n",
    "# =========================================\n",
    "\n",
    "print(\"Dataset Shape:\", df.shape)\n",
    "\n",
    "print(\"\\nColumn Names:\")\n",
    "print(df.columns)\n",
    "\n",
    "print(\"\\nData Types:\")\n",
    "print(df.dtypes)\n",
    "\n",
    "print(\"\\nMissing Values:\")\n",
    "print(df.isnull().sum())\n",
    "\n",
    "print(\"\\nDuplicate Rows:\")\n",
    "print(df.duplicated().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2326c93b-b6fc-408b-bbb5-7c60fde11962",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 4 ==================================\n",
    "# SUMMARY STATISTICS\n",
    "# =========================================\n",
    "\n",
    "df.describe().T"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "33100332-b1d4-439a-98aa-e3848ef7ccef",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 5 ==================================\n",
    "# DATA QUALITY FILTERING\n",
    "# =========================================\n",
    "\n",
    "df = df[\n",
    "    \n",
    "    (df['GrossProfit'] > 0)\n",
    "    &\n",
    "    (df['NetProfitMargin'] > 0)\n",
    "    &\n",
    "    (df['TotalQtySold'] > 0)\n",
    "    \n",
    "]\n",
    "\n",
    "print(\"Filtered Dataset Shape:\", df.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "37013f14-2988-4a77-bfd9-85bc06191b64",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 6 ==================================\n",
    "# FEATURE ENGINEERING\n",
    "# =========================================\n",
    "\n",
    "# Inventory Turnover\n",
    "df['StockTurnover'] = (\n",
    "    df['TotalQtySold']\n",
    "    /\n",
    "    df['TotalQtyPurchased']\n",
    ")\n",
    "\n",
    "# Sales Efficiency\n",
    "df['SalesEfficiency'] = (\n",
    "    df['TotalRevenue']\n",
    "    /\n",
    "    df['TotalSpend']\n",
    ")\n",
    "\n",
    "# Profit Per Unit\n",
    "df['ProfitPerUnit'] = (\n",
    "    df['NetProfit']\n",
    "    /\n",
    "    df['TotalQtySold']\n",
    ")\n",
    "\n",
    "# Vendor Dependency %\n",
    "total_spend = df['TotalSpend'].sum()\n",
    "\n",
    "df['VendorDependency%'] = (\n",
    "    df['TotalSpend']\n",
    "    /\n",
    "    total_spend\n",
    ") * 100\n",
    "\n",
    "# Order Size Classification\n",
    "df['OrderSize'] = pd.qcut(\n",
    "    df['TotalQtyPurchased'],\n",
    "    q=3,\n",
    "    labels=['Small', 'Medium', 'Large']\n",
    ")\n",
    "\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e84c8535-da8b-48b5-b316-3fa908ca76b1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 7 ==================================\n",
    "# DEAD STOCK RISK ANALYSIS\n",
    "# =========================================\n",
    "\n",
    "high_unsold = df['UnsoldInventoryValue'].quantile(0.75)\n",
    "\n",
    "low_turnover = df['StockTurnover'].quantile(0.25)\n",
    "\n",
    "df['DeadStockRisk'] = (\n",
    "\n",
    "    (df['UnsoldInventoryValue'] > high_unsold)\n",
    "    &\n",
    "    (df['StockTurnover'] < low_turnover)\n",
    "\n",
    ")\n",
    "\n",
    "df[['VendorName',\n",
    "    'UnsoldInventoryValue',\n",
    "    'StockTurnover',\n",
    "    'DeadStockRisk']].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6343287d-6410-4f29-ae1f-e604d7263531",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 8 ==================================\n",
    "# DISTRIBUTION PLOTS\n",
    "# =========================================\n",
    "\n",
    "numerical_cols = df.select_dtypes(include=np.number).columns\n",
    "\n",
    "# Dynamic rows calculation\n",
    "n_cols = 4\n",
    "n_rows = int(np.ceil(len(numerical_cols) / n_cols))\n",
    "\n",
    "plt.figure(figsize=(20, n_rows * 4))\n",
    "\n",
    "for i, col in enumerate(numerical_cols):\n",
    "\n",
    "    plt.subplot(n_rows, n_cols, i + 1)\n",
    "\n",
    "    sns.histplot(df[col], kde=True, bins=30)\n",
    "\n",
    "    plt.title(col)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e2801a72-bb8c-4aae-94fe-1f38de8e60d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 9 ==================================\n",
    "# OUTLIER ANALYSIS\n",
    "# =========================================\n",
    "\n",
    "n_cols = 4\n",
    "n_rows = int(np.ceil(len(numerical_cols) / n_cols))\n",
    "\n",
    "plt.figure(figsize=(20, n_rows * 4))\n",
    "\n",
    "for i, col in enumerate(numerical_cols):\n",
    "\n",
    "    plt.subplot(n_rows, n_cols, i + 1)\n",
    "\n",
    "    sns.boxplot(y=df[col])\n",
    "\n",
    "    plt.title(col)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bb019b6d-5e52-479a-b868-65c40c574634",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 10 =================================\n",
    "# CORRELATION ANALYSIS\n",
    "# =========================================\n",
    "\n",
    "plt.figure(figsize=(16,12))\n",
    "\n",
    "correlation_matrix = df[numerical_cols].corr()\n",
    "\n",
    "sns.heatmap(\n",
    "    correlation_matrix,\n",
    "    annot=True,\n",
    "    fmt='.2f',\n",
    "    cmap='coolwarm'\n",
    ")\n",
    "\n",
    "plt.title(\"Correlation Heatmap\")\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f76ee25-a6be-430a-a0c7-c38cc9467f07",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 11 =================================\n",
    "# TOP VENDORS & BRANDS\n",
    "# =========================================\n",
    "\n",
    "def format_currency(value):\n",
    "\n",
    "    if value >= 1_000_000:\n",
    "        return f\"${value/1_000_000:.2f}M\"\n",
    "\n",
    "    elif value >= 1_000:\n",
    "        return f\"${value/1_000:.2f}K\"\n",
    "\n",
    "    else:\n",
    "        return f\"${value:.2f}\"\n",
    "\n",
    "\n",
    "top_vendors = (\n",
    "    df.groupby('VendorName')['TotalRevenue']\n",
    "    .sum()\n",
    "    .nlargest(10)\n",
    ")\n",
    "\n",
    "top_brands = (\n",
    "    df.groupby('Description')['TotalRevenue']\n",
    "    .sum()\n",
    "    .nlargest(10)\n",
    ")\n",
    "\n",
    "plt.figure(figsize=(16,6))\n",
    "\n",
    "# Top Vendors\n",
    "plt.subplot(1,2,1)\n",
    "\n",
    "ax1 = sns.barplot(\n",
    "    y=top_vendors.index,\n",
    "    x=top_vendors.values,\n",
    "    palette='Blues_r'\n",
    ")\n",
    "\n",
    "plt.title(\"Top Vendors by Revenue\")\n",
    "\n",
    "for bar in ax1.patches:\n",
    "\n",
    "    ax1.text(\n",
    "        bar.get_width(),\n",
    "        bar.get_y() + bar.get_height()/2,\n",
    "        format_currency(bar.get_width()),\n",
    "        va='center'\n",
    "    )\n",
    "\n",
    "# Top Brands\n",
    "plt.subplot(1,2,2)\n",
    "\n",
    "ax2 = sns.barplot(\n",
    "    y=top_brands.index,\n",
    "    x=top_brands.values,\n",
    "    palette='Reds_r'\n",
    ")\n",
    "\n",
    "plt.title(\"Top Brands by Revenue\")\n",
    "\n",
    "for bar in ax2.patches:\n",
    "\n",
    "    ax2.text(\n",
    "        bar.get_width(),\n",
    "        bar.get_y() + bar.get_height()/2,\n",
    "        format_currency(bar.get_width()),\n",
    "        va='center'\n",
    "    )\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "13b1137d-d17e-4f23-be71-a006b93d229d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 12 =================================\n",
    "# VENDOR KPI SUMMARY\n",
    "# =========================================\n",
    "\n",
    "vendor_kpi = df.groupby('VendorName').agg({\n",
    "\n",
    "    'TotalSpend':'sum',\n",
    "    'TotalRevenue':'sum',\n",
    "    'NetProfit':'sum',\n",
    "    'NetProfitMargin':'mean',\n",
    "    'StockTurnover':'mean',\n",
    "    'UnsoldInventoryValue':'sum',\n",
    "    'TotalFreight':'sum'\n",
    "\n",
    "}).reset_index()\n",
    "\n",
    "vendor_kpi['Contribution%'] = (\n",
    "\n",
    "    vendor_kpi['TotalSpend']\n",
    "    /\n",
    "    vendor_kpi['TotalSpend'].sum()\n",
    "\n",
    ") * 100\n",
    "\n",
    "vendor_kpi.sort_values(\n",
    "    by='NetProfit',\n",
    "    ascending=False,\n",
    "    inplace=True\n",
    ")\n",
    "\n",
    "vendor_kpi.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "48c76940-6c0a-4fc1-a7d4-3a9fd970b0de",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 13 =================================\n",
    "# ABC VENDOR SEGMENTATION\n",
    "# =========================================\n",
    "\n",
    "vendor_kpi = vendor_kpi.sort_values(\n",
    "    by='TotalSpend',\n",
    "    ascending=False\n",
    ")\n",
    "\n",
    "vendor_kpi['CumulativeContribution'] = (\n",
    "    vendor_kpi['Contribution%'].cumsum()\n",
    ")\n",
    "\n",
    "def classify_vendor(x):\n",
    "\n",
    "    if x <= 70:\n",
    "        return 'A'\n",
    "\n",
    "    elif x <= 90:\n",
    "        return 'B'\n",
    "\n",
    "    else:\n",
    "        return 'C'\n",
    "\n",
    "vendor_kpi['VendorCategory'] = (\n",
    "    vendor_kpi['CumulativeContribution']\n",
    "    .apply(classify_vendor)\n",
    ")\n",
    "\n",
    "vendor_kpi.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81f9244c-c392-4a41-9622-9bc6cb2673c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 14 =================================\n",
    "# ABC CATEGORY DISTRIBUTION\n",
    "# =========================================\n",
    "\n",
    "plt.figure(figsize=(8,5))\n",
    "\n",
    "sns.countplot(\n",
    "    data=vendor_kpi,\n",
    "    x='VendorCategory',\n",
    "    palette='viridis'\n",
    ")\n",
    "\n",
    "plt.title(\"Vendor Distribution by ABC Category\")\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aca37c86-1b13-43da-a2ad-ca4cb4d5ee97",
   "metadata": {},
   "source": [
    "🔥 BUSINESS INSIGHT\n",
    "\n",
    "A Vendors → Critical suppliers\n",
    "\n",
    "B Vendors → Moderate importance\n",
    "\n",
    "C Vendors → Low-value suppliers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dae87eed-c822-462c-a486-2b1a4b978ca9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 15 =================================\n",
    "# PARETO ANALYSIS\n",
    "# =========================================\n",
    "\n",
    "vendor_sales = vendor_kpi.sort_values(\n",
    "    by='TotalRevenue',\n",
    "    ascending=False\n",
    ")\n",
    "\n",
    "vendor_sales['CumulativeSales%'] = (\n",
    "\n",
    "    vendor_sales['TotalRevenue'].cumsum()\n",
    "\n",
    "    /\n",
    "\n",
    "    vendor_sales['TotalRevenue'].sum()\n",
    "\n",
    ") * 100\n",
    "\n",
    "top_80_count = (\n",
    "    vendor_sales[\n",
    "        vendor_sales['CumulativeSales%'] <= 80\n",
    "    ]\n",
    "    .shape[0]\n",
    ")\n",
    "\n",
    "print(f\"\"\"\n",
    "Strategic Risk:\n",
    "{top_80_count} vendors contribute\n",
    "to 80% of total revenue.\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1fd12d0b-884f-4018-a447-8816c1a46a5c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 16 =================================\n",
    "# PARETO CHART\n",
    "# =========================================\n",
    "\n",
    "fig, ax1 = plt.subplots(figsize=(14,6))\n",
    "\n",
    "sns.barplot(\n",
    "    x=vendor_sales['VendorName'][:15],\n",
    "    y=vendor_sales['TotalRevenue'][:15],\n",
    "    ax=ax1,\n",
    "    palette='Blues_r'\n",
    ")\n",
    "\n",
    "ax1.set_xticklabels(\n",
    "    vendor_sales['VendorName'][:15],\n",
    "    rotation=90\n",
    ")\n",
    "\n",
    "ax1.set_ylabel(\"Revenue\")\n",
    "\n",
    "ax2 = ax1.twinx()\n",
    "\n",
    "ax2.plot(\n",
    "    vendor_sales['CumulativeSales%'][:15],\n",
    "    color='red',\n",
    "    marker='o'\n",
    ")\n",
    "\n",
    "ax2.axhline(\n",
    "    y=80,\n",
    "    color='black',\n",
    "    linestyle='--'\n",
    ")\n",
    "\n",
    "ax2.set_ylabel(\"Cumulative Revenue %\")\n",
    "\n",
    "plt.title(\"Pareto Analysis - Vendor Revenue Contribution\")\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "09020ef3-f494-402e-9948-41c5d44d6097",
   "metadata": {},
   "source": [
    "### Pareto Analysis — Business Insights\n",
    "\n",
    "#### Key Findings\n",
    "\n",
    "- A small group of vendors contributes the majority of total revenue.\n",
    "\n",
    "- This reflects a strong concentration of revenue dependency on limited suppliers.\n",
    "\n",
    "#### Business Risk\n",
    "\n",
    "- Heavy reliance on a few vendors increases supplier dependency risk and operational vulnerability.\n",
    "\n",
    "#### Strategic Recommendations\n",
    "\n",
    "- Diversify procurement across additional high-potential vendors.\n",
    "\n",
    "- Closely monitor strategic vendors contributing major revenue share.\n",
    "\n",
    "- Build contingency supplier plans to reduce procurement and supply chain risk."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3583ff59-819d-461d-b404-13aa151cb53e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 17 =================================\n",
    "# BULK PURCHASE ANALYSIS\n",
    "# =========================================\n",
    "\n",
    "plt.figure(figsize=(10,6))\n",
    "\n",
    "sns.boxplot(\n",
    "    data=df,\n",
    "    x='OrderSize',\n",
    "    y='ActualPaidPrice',\n",
    "    palette='Set2'\n",
    ")\n",
    "\n",
    "plt.title(\"Bulk Purchasing Impact on Unit Cost\")\n",
    "\n",
    "plt.xlabel(\"Order Size\")\n",
    "\n",
    "plt.ylabel(\"Unit Cost\")\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "76c950b7-ad85-45ed-bfae-2cdf0cd5cd1c",
   "metadata": {},
   "source": [
    "### Bulk Purchase Analysis — Business Insights\n",
    "\n",
    "#### Key Findings\n",
    "\n",
    "- Vendors placing larger procurement orders achieve significantly lower average unit costs compared to small-order vendors.\n",
    "\n",
    "- Large order sizes demonstrate stronger purchasing power and better supplier negotiation efficiency, which directly improves profitability potential.\n",
    "\n",
    "- The difference in unit purchase cost between small and large orders is substantial, indicating the presence of effective bulk pricing strategies from suppliers.\n",
    "\n",
    "#### Business Interpretation\n",
    "\n",
    "- Bulk procurement helps reduce per-unit acquisition costs, allowing vendors to maintain healthier profit margins while remaining competitive in pricing.\n",
    "\n",
    "- Vendors with efficient inventory movement can benefit the most from high-volume purchasing because lower procurement costs increase overall margin potential.\n",
    "\n",
    "- However, excessive bulk purchasing without sufficient sales velocity may increase inventory holding costs and dead stock risk.\n",
    "\n",
    "#### Strategic Recommendations\n",
    "\n",
    "- Increase procurement volume for high-demand and fast-moving products to maximize bulk pricing advantages.\n",
    "\n",
    "- Avoid aggressive bulk purchasing for slow-moving inventory to reduce working capital lock-in.\n",
    "\n",
    "- Implement demand forecasting before large procurement decisions to balance inventory efficiency and cost savings.\n",
    "\n",
    "- Negotiate long-term supplier contracts for high-performing vendors to further optimize unit economics."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a6ee55c1-b56d-480c-b87c-e2c75eede064",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 18 =================================\n",
    "# HIGH MARGIN LOW SALES PRODUCTS\n",
    "# =========================================\n",
    "\n",
    "\n",
    "brand_performance = df.groupby('Description').agg({\n",
    "\n",
    "    'TotalRevenue':'sum',\n",
    "    'NetProfitMargin':'mean'\n",
    "\n",
    "}).reset_index()\n",
    "\n",
    "low_sales_threshold = (\n",
    "    brand_performance['TotalRevenue']\n",
    "    .quantile(0.15)\n",
    ")\n",
    "\n",
    "high_margin_threshold = (\n",
    "    brand_performance['NetProfitMargin']\n",
    "    .quantile(0.85)\n",
    ")\n",
    "\n",
    "target_brands = brand_performance[\n",
    "\n",
    "    (brand_performance['TotalRevenue']\n",
    "     <= low_sales_threshold)\n",
    "\n",
    "    &\n",
    "\n",
    "    (brand_performance['NetProfitMargin']\n",
    "     >= high_margin_threshold)\n",
    "\n",
    "]\n",
    "\n",
    "target_brands.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b66b4c77-c9b2-40ec-8dc7-cd19ba53d947",
   "metadata": {},
   "source": [
    "🔥 BUSINESS INSIGHT\n",
    "Some vendors have extremely high logistics costs.\n",
    "\n",
    "Possible reasons:\n",
    "- inefficient shipping\n",
    "- low order consolidation\n",
    "- distant suppliers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ffb6148-5f4b-42a1-a9b2-72624ff5f3c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 19 =================================\n",
    "# TARGET BRAND VISUALIZATION\n",
    "# =========================================\n",
    "\n",
    "plt.figure(figsize=(10,6))\n",
    "\n",
    "sns.scatterplot(\n",
    "    data=brand_performance,\n",
    "    x='TotalRevenue',\n",
    "    y='NetProfitMargin',\n",
    "    alpha=0.3,\n",
    "    label='All Brands'\n",
    ")\n",
    "\n",
    "sns.scatterplot(\n",
    "    data=target_brands,\n",
    "    x='TotalRevenue',\n",
    "    y='NetProfitMargin',\n",
    "    color='red',\n",
    "    label='Target Brands'\n",
    ")\n",
    "\n",
    "plt.axhline(\n",
    "    high_margin_threshold,\n",
    "    linestyle='--'\n",
    ")\n",
    "\n",
    "plt.title(\"High Margin Low Sales Products\")\n",
    "\n",
    "plt.xlabel(\"Revenue\")\n",
    "\n",
    "plt.ylabel(\"Net Profit Margin\")\n",
    "\n",
    "plt.legend()\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a5275c6d-2c5b-4459-8281-0aa5de5a7cf8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 20 =================================\n",
    "# HYPOTHESIS TESTING\n",
    "# =========================================\n",
    "\n",
    "top_threshold = df['TotalRevenue'].quantile(0.75)\n",
    "\n",
    "low_threshold = df['TotalRevenue'].quantile(0.25)\n",
    "\n",
    "top_vendors = (\n",
    "    df[df['TotalRevenue'] >= top_threshold]\n",
    "    ['NetProfitMargin']\n",
    ")\n",
    "\n",
    "low_vendors = (\n",
    "    df[df['TotalRevenue'] <= low_threshold]\n",
    "    ['NetProfitMargin']\n",
    ")\n",
    "\n",
    "t_stat, p_value = ttest_ind(\n",
    "    top_vendors,\n",
    "    low_vendors,\n",
    "    equal_var=False\n",
    ")\n",
    "\n",
    "print(f\"T-Statistic: {t_stat:.4f}\")\n",
    "\n",
    "print(f\"P-Value: {p_value:.4f}\")\n",
    "\n",
    "if p_value < 0.05:\n",
    "\n",
    "    print(\"\"\"\n",
    "Reject Null Hypothesis:\n",
    "Significant difference exists between\n",
    "top and low performing vendors.\n",
    "\"\"\")\n",
    "\n",
    "else:\n",
    "\n",
    "    print(\"\"\"\n",
    "Fail to Reject Null Hypothesis:\n",
    "No significant difference found.\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "05ee41fa-3ce0-44f4-be54-30aaecb06344",
   "metadata": {},
   "source": [
    "### Statistical Analysis — Business Insights\n",
    "\n",
    "#### Key Findings\n",
    "\n",
    "- Low-performing vendors show higher average profit margins compared to top-performing vendors.\n",
    "\n",
    "- This indicates that lower-sales vendors may rely on premium pricing strategies or operate with lower operational pressure.\n",
    "\n",
    "- High-performing vendors generate larger revenue volumes but often operate with comparatively tighter margins.\n",
    "\n",
    "#### Hypothesis Testing Result\n",
    "\n",
    "- Null Hypothesis (H₀): No significant difference exists in profit margins between top and low-performing vendors.\n",
    "\n",
    "- Alternative Hypothesis (H₁): A significant difference exists in profit margins between top and low-performing vendors.\n",
    "\n",
    "- Based on the T-Test results, the business can statistically validate whether vendor profitability behavior differs across performance groups.\n",
    "\n",
    "#### Business Recommendations\n",
    "\n",
    "- Improve margin optimization strategies for high-revenue vendors through pricing and operational efficiency.\n",
    "\n",
    "- Strengthen marketing and distribution strategies for low-performing vendors to improve sales volume.\n",
    "\n",
    "- Use statistical analysis to support data-driven vendor pricing and procurement decisions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7977bc97-fe33-4662-832e-e52f02515edf",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 21 =================================\n",
    "# RECOMMENDATION ENGINE\n",
    "# =========================================\n",
    "\n",
    "df_final = df.merge(\n",
    "\n",
    "    vendor_kpi[\n",
    "        [\n",
    "            'VendorName',\n",
    "            'VendorCategory',\n",
    "            'Contribution%',\n",
    "            'CumulativeContribution'\n",
    "        ]\n",
    "    ],\n",
    "\n",
    "    on='VendorName',\n",
    "    how='left'\n",
    "\n",
    ")\n",
    "\n",
    "margin_median = df_final['NetProfitMargin'].median()\n",
    "\n",
    "def recommend_action(row):\n",
    "\n",
    "    if row['DeadStockRisk'] == True:\n",
    "        return 'Liquidate Excess Inventory'\n",
    "\n",
    "    elif (\n",
    "        row['VendorCategory'] == 'A'\n",
    "        and row['NetProfitMargin'] < margin_median\n",
    "    ):\n",
    "        return 'Negotiate Better Vendor Pricing'\n",
    "\n",
    "    elif (\n",
    "        row['VendorCategory'] == 'C'\n",
    "        and row['StockTurnover'] < 1\n",
    "    ):\n",
    "        return 'Reduce Procurement Dependency'\n",
    "\n",
    "    elif row['FreightPerUnit'] > df_final['FreightPerUnit'].quantile(0.75):\n",
    "        return 'Optimize Freight & Logistics'\n",
    "\n",
    "    elif (\n",
    "        row['SalesEfficiency'] > 1.2\n",
    "        and row['StockTurnover'] > 1\n",
    "    ):\n",
    "        return 'Increase Procurement Volume'\n",
    "\n",
    "    else:\n",
    "        return 'Maintain Current Strategy'\n",
    "\n",
    "df_final['RecommendedAction'] = (\n",
    "    df_final.apply(recommend_action, axis=1)\n",
    ")\n",
    "\n",
    "df_final.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "698c99a4-9521-4770-a2ed-f809dfdbe236",
   "metadata": {},
   "source": [
    "### Executive Business Recommendations\n",
    "\n",
    "1. Reduce dependency on high-concentration vendors to minimize supplier risk.\n",
    "\n",
    "2. Optimize freight-intensive vendors to improve logistics efficiency.\n",
    "\n",
    "3. Promote high-margin low-sales products through targeted marketing campaigns.\n",
    "\n",
    "4. Reduce dead stock inventory to unlock working capital.\n",
    "\n",
    "5. Prioritize procurement for high-turnover products and vendors.\n",
    "\n",
    "6. Improve pricing strategies for low-performing vendors.\n",
    "\n",
    "7. Use ABC segmentation for vendor prioritization and strategic sourcing."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5a99aca5-aa8b-44ab-8d03-55bdd2a8bbdc",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 22 =================================\n",
    "# EXPORT FINAL DASHBOARD DATASET\n",
    "# =========================================\n",
    "\n",
    "df_final.drop_duplicates(inplace=True)\n",
    "\n",
    "output_path = r\"C:\\Users\\ASUS\\Desktop\\_aPortfolioProjects\\Vendor Intelligence & Procurement Optimization Analytics System\\cleaned_data\"\n",
    "\n",
    "import os\n",
    "os.makedirs(output_path, exist_ok=True)\n",
    "\n",
    "df_final.to_csv(\n",
    "    os.path.join(output_path, \"vendor_intelligence_final.csv\"),\n",
    "    index=False\n",
    ")\n",
    "\n",
    "print(\"✅ File Saved Successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dc4edb45-39d3-4bfd-921c-191c371f1a44",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (TensorFlow)",
   "language": "python",
   "name": "tf_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
